console.log('🔍 Render Database Credentials Helper');
console.log('=====================================');
console.log('');
console.log('To fix your database connection, you need to:');
console.log('');
console.log('1. Go to your Render dashboard: https://dashboard.render.com');
console.log('2. Find your PostgreSQL database service (should be named something like "crm-database")');
console.log('3. Click on it and go to "Environment" tab');
console.log('4. Copy these values:');
console.log('   - Internal Database URL (looks like: postgresql://user:pass@host:port/db)');
console.log('   - Or individual values: Host, Port, Database, Username, Password');
console.log('');
console.log('5. Then run this command with your actual credentials:');
console.log('   npm run setup-postgresql');
console.log('');
console.log('Current environment variables:');
console.log('   DB_DRIVER:', process.env.DB_DRIVER || 'NOT SET');
console.log('   DATABASE_URL:', process.env.DATABASE_URL ? 'SET' : 'NOT SET');
console.log('   DB_HOST:', process.env.DB_HOST || 'NOT SET');
console.log('   DB_USER:', process.env.DB_USER || 'NOT SET');
console.log('   DB_NAME:', process.env.env.DB_NAME || 'NOT SET');
console.log('   DB_PASSWORD:', process.env.DB_PASSWORD ? 'SET' : 'NOT SET');
console.log('');
console.log('If you have the DATABASE_URL, create a .env file with:');
console.log('DATABASE_URL=your_actual_database_url_here');
console.log('DB_DRIVER=postgresql');
console.log('');
console.log('Or set these environment variables in Render dashboard for your backend service.');
